# Fluid 主题配置文件
# 覆盖主题默认配置

# 导航栏配置
navbar:
  # 导航栏左上角的标题，为空则按 hexo config.title 显示
  blog_title: "云端FFF的博客"

# 首页配置
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: /img/default.png
  
  # 头图高度，屏幕百分比
  banner_height: 100
  
  # 头图黑色蒙版的不透明度，available: 0 - 1.0， 1 是完全不透明
  banner_mask_alpha: 0.3
  
  # 首页副标题的独立设置
  slogan:
    enable: true
    # 为空则按 hexo config.subtitle 显示
    text: "Not because they are easy, but because they are hard"
    # 通过 API 接口作为首页副标题
    # 请先设置上面 text 为空，再开启下面的配置
    api:
      # 请求地址
      url: ""
      # 请求方法
      method: "GET"
      # 请求头
      headers: {}
      # 从请求结果获取字符串的取值字段，最终必须是一个字符串
      keys: []

# 一些好玩的功能
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: true
    # 打印速度，数字越大越慢
    typeSpeed: 50
    # 游标字符
    cursorChar: "_"
    # 是否循环播放效果
    loop: false
    # 在指定页面开启，不填则在所有页面开启
    scope: []

# 关于页配置
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "云端FFF"
  introduce: "Stay Hungry, Stay Foolish"
  # 更多个人信息
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/wxc971231", tip: "GitHub" }
    - { class: "iconfont icon-email", link: "mailto:wwxc971231@163.com", tip: "邮箱" }
    - { class: "iconfont icon-bilibili-fill", link: "https://space.bilibili.com/4625838", tip: "Bilibili" }
    - { class: "iconfont icon-csdn", link: "https://blog.csdn.net/wxc971231", tip: "CSDN" }

# 自定义 CSS
custom_css: /css/iconfont/iconfont.css