# Fluid 主题配置文件
# 覆盖主题默认配置

# 首页配置
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: /img/default.png
  
  # 头图高度，屏幕百分比
  banner_height: 100
  
  # 头图黑色蒙版的不透明度，available: 0 - 1.0， 1 是完全不透明
  banner_mask_alpha: 0.3
  
  # 首页副标题的独立设置
  slogan:
    enable: true
    # 为空则按 hexo config.subtitle 显示
    text: "欢迎来到云端fff的技术博客 - 分享技术，记录生活"
    # 通过 API 接口作为首页副标题
    # 请先设置上面 text 为空，再开启下面的配置
    api:
      # 请求地址
      url: ""
      # 请求方法
      method: "GET"
      # 请求头
      headers: {}
      # 从请求结果获取字符串的取值字段，最终必须是一个字符串
      keys: []

# 一些好玩的功能
fun_features:
  # 为 subtitle 添加打字机效果
  typing:
    enable: true
    # 打印速度，数字越大越慢
    typeSpeed: 70
    # 游标字符
    cursorChar: "_"
    # 是否循环播放效果
    loop: false
    # 在指定页面开启，不填则在所有页面开启
    scope: []