name: Deploy Hexo Blog

on:
  push:
    branches:
      - source  # 当推送到 source 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写权限来推送到 main 分支
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: source
        fetch-depth: 0  # 获取完整历史记录
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Clean and generate
      run: |
        npx hexo clean
        npx hexo generate
        
    - name: Deploy to main branch
      run: |
        cd public
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy from source branch - $(date)"
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main